### ISSUE TITLE
I Cloned Master, But I met problem...

### ISSUE THREAD

**Issue by luohc2004** [ar1st0crat/Blackjack#1]
I Debuged solution in vs2015 community, and I meet an “System.NullReferenceException”:
StackTrace:
   在 Blackjack.MainForm.MainForm_Resize(Object sender, EventArgs e) 位置 D:\MyDocuments\Visual Studio 2015\Projects\BlackJack2\Blackjack\View\MainForm.cs:行号 224
   在 System.Windows.Forms.Control.OnResize(EventArgs e)
   在 System.Windows.Forms.Form.OnResize(EventArgs e)
   在 System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   在 System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   在 System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height)
   在 System.Windows.Forms.Control.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
   在 System.Windows.Forms.Form.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
   在 System.Windows.Forms.Control.ScaleControl(SizeF factor, BoundsSpecified specified)
   在 System.Windows.Forms.ScrollableControl.ScaleControl(SizeF factor, BoundsSpecified specified)
   在 System.Windows.Forms.Form.ScaleControl(SizeF factor, BoundsSpecified specified)
   在 System.Windows.Forms.Control.ScaleControl(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
   在 System.Windows.Forms.ContainerControl.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
   在 System.Windows.Forms.ContainerControl.PerformAutoScale(Boolean includedBounds, Boolean excludedBounds)
   在 System.Windows.Forms.ContainerControl.PerformNeededAutoScaleOnLayout()
   在 System.Windows.Forms.ContainerControl.OnLayoutResuming(Boolean performLayout)
   在 System.Windows.Forms.Control.ResumeLayout(Boolean performLayout)
   在 Blackjack.MainForm.InitializeComponent() 位置 D:\MyDocuments\Visual Studio 2015\Projects\BlackJack2\Blackjack\View\MainForm.Designer.cs:行号 47
   在 Blackjack.MainForm..ctor() 位置 D:\MyDocuments\Visual Studio 2015\Projects\BlackJack2\Blackjack\View\MainForm.cs:行号 35
   在 Blackjack.Program.Main() 位置 D:\MyDocuments\Visual Studio 2015\Projects\BlackJack2\Blackjack\Program.cs:行号 17
   在 System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   在 System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   在 Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   在 System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Threading.ThreadHelper.ThreadStart()

the parameter goes null is: CardTableVisualizer gamevisualizer

**Comment by ar1st0crat** [comment]
Interesting. I couldn't reproduce the problem in vs2012. In my case the Load event of MainForm is fired always _before_ the Resize event. But it seems that this order of events is not guaranteed.
I made a fix, so pull the new version, please. Thanks for noticing.
Also, since you are using Debug mode, don't forget to put Cards.dll in your bin/Debug folder.
Hope this helps.

**Comment by luohc2004** [comment]
I'll update to the new version and have a go, as soon as I'm freed from all those works. Thank you very much.
